name: Server checks

on:
  push:
    branches:
      - main
    paths:
      - "./server/**"

jobs:
  server-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Format
        run: cargo fmt
      - name: Clippy
        run: cargo clippy
      - name: Build
        run: cargo build
